language: cpp
sudo: required
dist: trusty
services:
- docker
python:
- '2.7'
compiler:
- gcc
os:
- linux
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: cEo+MZxkDk0sHNd0eVVJdvxMvNCGcQqHSXXUT/Txq30N5y0qGmWgqr1onFPJ9kjswdQotbJMrrgup96YovpkaqNqv/ydptX6yoRzmOX7ZADlicdBlLCtMlaE1lgu47Vdydu8Lc7HybjdVIFtJQOUqO89dhQO1vfOrIqypLWBNxffuGjwZBmMze8eldviQwilVeQw9V8/IfvIGMpmAf+hSUUrAw6QZTxAN7mrZ7qqIG+sdm1m5FBMp6mna6MzAiC0PrIb8YJTBNE5NG6u0mu9RrlTgkS6/7k2j+HFLfEN7jzNlIRSnBOKdUvhfOmTylsj9WxwR3aRALgxgREqnY50zqpNDRLfd3c3m7yPFZ3LzRV9N/d6BkMruWwRkkYS4DLNSKGjeLIOfp+HzaPoG19pcYxfk9MIhkv/SILiZizYZUBzf91QrSOJ/n2sIcKvqDufisFPJcfKpXtIQ3o19cfupYPbU/De4I0reiVLrTQ+2HbynYBwN5XqXPXvjNuYuRLes5AfGg9RL68wdcIGxzKQ+E4BxpnubQgVhON7+XM0UnlVNbZrm0WOXRGypvuTkERQDJZ+cTVjMQlHq0EY/GJ/fwUkCGEPhGz1WrQGNTKS8J9AL/4MFsNJtlxSkek8rP0p548R4LiJ5hxyVjrefRoaJDfi+vmKJTaFvn3pjc3otoM=
  - secure: Q2glMCq7Z9JqZzA6bPRC1KvhDbYyAsm4ve7V8bHJJSi3CYohuNkD3hdUWp1RH+dUudge5QwYdTWBaqwZ8MVrB9Ve3Jc1kQa+xMr7ZbQ61lcSdohaDoIGFnOl+5mf4Ewm7d0DLwhQdyicrgVuCmrr2G10kpD7kq7+E1XXhEYMhTjfzKdCl6caBNVTYsk4jLDNxKhUqD6/MMVXHe/tA6CRrHZOyApY+EkrRiiagAnnDxlojGmHmj7qqF6u0LBzWTbQV6nFnL4fCi87tm9AxwpEtK9cOTKR8DTwwzL6RGJf3kyIDtFOA4M2lEFDY7k8ek7jugGbryriRCLaz22dVEmgIpUA2Ab/pDVhd1BhZVa+LTd7uRrzRzIbsKMXQDi47Oxu1Au8CQbVdcww1seXBSJdyW5jAZbH/lkJQGRGxw7QbOCzATdv/CgoipTFHlklNouFL2ojSl2zUmrJyXHk5fdUvANlnLffRUei0fkF5oprzI7xxgxedEYqSbdbv3T5WSMCYgX3yvrRrj27frNDBDI9Ms7csFjD2XQIqDgKN2PrgUGtWsM6l/CsseA5cBFwomN8PtT3k6NjafFbJ339GFkw7244EYKXKFiE3bILTg5sNpRiB6UYZ6fFzFTDCfMGOWIsID5zGbYgARxZdf55sq5dRofbBJXCaqssLgZbNxpJ72M=
  - secure: W9wV7IW00uhHhdD1ui+j0oH5g/snp58Vg0PFCBwWKp8uGRM30flT1NNoGkMSTJtYmGLlUlqViyoQlWEouSHV08cwJBv/Xe48CUgTbXz0x2QoNCr9Zo3Mwj8NZYCItzl4kkqTjbZNRnOlXUwMVcbpPLiZKG9qIO0da/rt16wiX4OjUR6j6AZ3Js72zy360WA8tX4tyZnAqVuMoC0o4rp6GnUDkTRraYMX4t1zeIKdWejwb1R3jMVPCIDtALJLqm0dpqpfdJNufGInw1wu76IQYzO8xD3YXxK/q+lUDXN1WTSlfYOjeAoImkIwmZB9tTGI/8ntRwErp6HUcIlLq2nTU1uTo2/FD+NS+aPenddeS0Y4QdL07EJhrdTu/w7fGpGWWYVbsZSRqN+qIfSNHhRwhkoXCR2DO/a8QvYI9YZmcEXS2IUiE9rZpWCJz3d0R7t423DHBvyPXyLZRwrz8tMIv3/2Bg++W8SYOcDpQeaxUxvpHh7B7ZwyZaB+e5ckU5/lOqB22yxC8EWpgXXAnwqfVVWum3qB1UyOh9gaRdI8Oj+lJ1S/pM2SAkMNxMpMC0sA14PQp4eC+Es//Ocg2RyKqoQyv5/2S7vcb9fBjTdcqQhLbrocIYnaapdf/g/JgbsMgUc9Hv74e+sLzs9E2NJe5dpNy/OJQ4+wYa/iJUUcVhY=
before_install:
- echo $LANG
- echo $LC_ALL
before_script:
install:
script:
- docker build -f Dockerfile -t $TRAVIS_REPO_SLUG:$COMMIT .
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag $TRAVIS_REPO_SLUG:$COMMIT $TRAVIS_REPO_SLUG:$TAG
- docker tag $TRAVIS_REPO_SLUG:$COMMIT $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_NUMBER
- docker push $TRAVIS_REPO_SLUG
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  email:
  - allixender@googlemail.com
